### ISSUE TITLE
Python<3.6 compat

### ISSUE THREAD

**Issue by martmists** [IzunaDevs/SnekChek#1]
We're using a lot of f-strings, they should be reworked to str.format to support lower versions of python.

**Comment by AraHaan** [comment]
Maybe an shortcut function could do it, however then how would I substitute it for an f string if python >= 3.6?

perhaps the only way is to figure out how to similate the f strings?

**Comment by martmists** [comment]
what the hell did you smoke

It's just gonna be `"{}".format(...)` instead of `f"{}"`

That code you provided will fail either way and won't even work...

**Comment by AraHaan** [comment]
Ah I see.
