### ISSUE TITLE
Mypy

### ISSUE THREAD

**Issue by hargoniX** [IzunaDevs/SnekChek#13]
I would try to add mypy support if that is ok for you

**Comment by martmists** [comment]
We've had issues with `flake8-mypy` in the past, but if you can make this work then go ahead.

**Comment by hargoniX** [comment]
May I ask which issues?

**Comment by martmists** [comment]
Something about structure files not being found? check way back in travis history

**Comment by martmists** [comment]
flake8-mypy seems to work fine now.
