### ISSUE TITLE
Config file isn't being detected

### ISSUE THREAD

**Issue by noud02** [IzunaDevs/SnekChek#5]
![image](https://user-images.githubusercontent.com/21309207/35432496-8e72b096-0280-11e8-8a38-7bbe0fa17c5e.png)
![image](https://user-images.githubusercontent.com/21309207/35432509-9c3b7c58-0280-11e8-88d1-a7071f9f9d95.png)

Passing `--config-file=./.snekrc` also doesn't work.
![image](https://user-images.githubusercontent.com/21309207/35432551-c162411a-0280-11e8-9bfe-23431685e727.png)

**Comment by martmists** [comment]
That's a message pylint sends out for some reason, looking into muting that or something

**Comment by martmists** [comment]
Closing because config is found and used. Just missing a pylint config
