### ISSUE TITLE
Run only on single file

### ISSUE THREAD

**Issue by hargoniX** [IzunaDevs/SnekChek#9]
What about adding an option for only running snekchek on a single file instead of the whole project

**Comment by martmists** [comment]
This might cause issues on some linters as some will do all files without us being able to influence it, but this seems like an interesting suggestion.

**Comment by martmists** [comment]
This has been added to 2bb81a9671773a2c40d2b8599a731e66a8400bc1 and will be further enhanced in the future.

**Comment by hargoniX** [comment]
This would be very important for me especially. The linter framework for atom just waits a certain time until a linter process finishes and just throws an error when it takes too long.
